name: Build CEQR Dataset
run-name: "Build CEQR Dataset: ${{ inputs.dataset }}"

on:
  workflow_dispatch:
    inputs:
      dataset:
        description: "Dataset to build"
        required: true

jobs:
  build:
    if: >-
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      RECIPE_ENGINE: ${{ secrets.RECIPE_ENGINE }}
      EDM_DATA: ${{ secrets.EDM_DATA }}
      AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3

      # - name: Setup python
      #   uses: actions/setup-python@v4.5.0
      #   with:
      #     python-version: "3.11.1"

      - name: Install dependencies
        shell: bash
        run: ./ceqr setup

      - name: Run recipe
        shell: bash
        run: ./ceqr run recipe ${{ inputs.dataset }}
