name: Monthly Run DEP CATS permits
on:
  schedule:
    - cron: 0 0 1 * *
  repository_dispatch:
    types: [dep_cats_permits]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RECIPE_ENGINE: ${{ secrets.RECIPE_ENGINE }}
      EDM_DATA: ${{ secrets.EDM_DATA }}
      AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
        
      - name: Install dependencies
        shell: bash
        run: ./ceqr setup
        
      - name: Run recipe
        shell: bash
        run: ./ceqr run recipe dep_cats_permits
  
      - uses: nashmaniac/create-issue-action@v1.1
        name: Create Issue to Publish
        with:
          title: |
            [publish] dep_cats_permits
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: rtblair
          labels: publish
          body: |
            A fresh run of dep_cats_permits is complete! 🎉

            ## Staging files output:
            - [ ] [version.txt](https://nyc3.digitaloceanspaces.com/edm-publishing/ceqr-app-data-staging/dep_cats_permits/latest/version.txt)
            - [ ] [dep_cats_permits.zip](https://nyc3.digitaloceanspaces.com/edm-publishing/ceqr-app-data-staging/dep_cats_permits/latest/dep_cats_permits.zip)
            - [ ] [dep_cats_permits.csv](https://nyc3.digitaloceanspaces.com/edm-publishing/ceqr-app-data-staging/dep_cats_permits/latest/dep_cats_permits.csv)
            - [ ] [ReadMe_DEPCATS.pdf](https://nyc3.digitaloceanspaces.com/edm-publishing/ceqr-app-data-staging/dep_cats_permits/latest/ReadMe_DEPCATS.pdf)

            ## Next Steps: 
            If you have manually checked above files and they seem to be ok, comment `[publish]` under this issue. 
            This would allow github actions to move staging files to production. 
            Feel free to close this issue once it's all complete. Thanks!
