name: Run CEQR Recipe
on:
  issues:
    types: [opened, edited]

jobs:
  push:
    if: >- 
      contains(github.event.issue.title, '[build]') && 
      (
        github.event.comment.user.login == 'mgraber'||
        github.event.comment.user.login == 'SPTKL'||
        github.event.comment.author_association == 'MEMBER'
      )
    runs-on: ubuntu-latest
    env:
      RECIPE_ENGINE: ${{ secrets.RECIPE_ENGINE }}
      EDM_DATA: ${{ secrets.EDM_DATA }}
      AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
        
      - name: Install dependencies
        shell: bash
        run: ./ceqr setup
      
      - name: Parse dataset names
        shell: python
        id: parsing
        run: |
          import os
          
          body = """${{ github.event.issue.body }}"""
          splited = body.split('\n')
          start = splited.index("```yml")+1
          end = splited.index("```")
          datasets=' '.join([i[2:] for i in splited[start:end]])
          os.system('echo "::set-output name=datasets::{0}"'.format(datasets))
                  
      - name: Datasets to update...
        run: echo "${{ steps.parsing.outputs.datasets }}"

      - name: Run recipes
        shell: bash
        run: |
          for i in ${{ steps.parsing.outputs.datasets }}
          do
            ./ceqr run recipe $i
          done
          
      - name: Success Message
        if: success()
        uses:  peter-evans/close-issue@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: |
            ## CEQR datasets successfully updated!
            
            ${{ steps.parsing.outputs.datasets }}
            
            *Updated by: @${{ github.actor }}* for more details, check https://github.com/NYCPlanning/ceqr-app-data/actions/runs/${{ github.run_id }}
      